# generated by appcreator
from django.contrib import admin
from .models import Court, CourtDecission, KeyWord, PartialLegalSystem, Person, Tag

admin.site.register(Court)
admin.site.register(CourtDecission)
admin.site.register(KeyWord)
admin.site.register(PartialLegalSystem)
admin.site.register(Person),
admin.site.register(Tag)
