# generated by appcreator
from django.contrib import admin
from .models import (
    Country,
    Court,
    CourtDecission,
    KeyWord,
    PartialLegalSystem,
    Person,
)

admin.site.register(Country)
admin.site.register(Court)
admin.site.register(CourtDecission)
admin.site.register(KeyWord)
admin.site.register(PartialLegalSystem)
admin.site.register(Person)
