# generated by appcreator
from django.contrib import admin

from .models import Court
from .models import CourtDecission
from .models import KeyWord
from .models import PartialLegalSystem
from .models import Person
from .models import Tag

admin.site.register(Court)
admin.site.register(CourtDecission)
admin.site.register(KeyWord)
admin.site.register(PartialLegalSystem)
admin.site.register(Person)
admin.site.register(Tag)
