# generated by appcreator
from dal import autocomplete
from django.db.models import Q

from .models import Court
from .models import CourtDecission
from .models import KeyWord
from .models import PartialLegalSystem
from .models import Person
from .models import Tag
from .models import YearBook


class YearBookAC(autocomplete.Select2QuerySetView):
    def get_queryset(self):
        qs = YearBook.objects.all()

        if self.q:
            qs = qs.filter(title__icontains=self.q)
        return qs


class MonographAC(autocomplete.Select2QuerySetView):
    def get_queryset(self):
        qs = YearBook.objects.exclude(has_bibliographic_items=None)

        if self.q:
            qs = qs.filter(title__icontains=self.q)
        return qs


class CourtAC(autocomplete.Select2QuerySetView):
    def get_queryset(self):
        qs = Court.objects.all()

        if self.q:
            qs = qs.filter(Q(name__icontains=self.q))
        return qs


class CourtDecissionAC(autocomplete.Select2QuerySetView):
    def get_queryset(self):
        qs = CourtDecission.objects.all()

        if self.q:
            qs = qs.filter(Q(id__icontains=self.q))
        return qs


class KeyWordAC(autocomplete.Select2QuerySetView):
    def get_queryset(self):
        qs = KeyWord.objects.all()

        if self.q:
            qs = qs.filter(Q(id__icontains=self.q) | Q(name__icontains=self.q))
        return qs


class PartialLegalSystemAC(autocomplete.Select2QuerySetView):
    def get_queryset(self):
        qs = PartialLegalSystem.objects.all()

        if self.q:
            qs = qs.filter(Q(name__icontains=self.q) | Q(id__icontains=self.q))
        return qs


class PersonAC(autocomplete.Select2QuerySetView):
    def get_queryset(self):
        qs = Person.objects.all()

        if self.q:
            qs = qs.filter(
                Q(first_name__icontains=self.q) | Q(last_name__icontains=self.q)
            )
        return qs


class TagAC(autocomplete.Select2QuerySetView):
    def get_queryset(self):
        qs = Tag.objects.all()

        if self.q:
            qs = qs.filter(Q(tag__icontains=self.q) | Q(id__icontains=self.q))
        return qs
