# generated by appcreator
import django_tables2 as tables
from browsing.utils import MergeColumn

from .models import (
    Court,
    CourtDecission,
    KeyWord,
    PartialLegalSystem,
    Person,
    Tag,
    YearBook,
)


class ResultsTable(tables.Table):
    id = tables.LinkColumn(verbose_name="ID")
    full_text = tables.columns.TemplateColumn(
        template_code="{{ record.full_text|safe }}"
    )

    class Meta:
        model = CourtDecission
        fields = (
            "id",
            "date_written",
            "full_text",
        )
        sequence = ("id",)
        attrs = {"class": "table table-responsive table-hover"}


class YearBookTable(tables.Table):
    id = tables.LinkColumn(verbose_name="ID")
    merge = MergeColumn(verbose_name="keep | remove", accessor="pk")

    class Meta:
        model = YearBook
        sequence = ("id",)
        attrs = {"class": "table table-responsive table-hover"}


class CourtTable(tables.Table):
    id = tables.LinkColumn(verbose_name="ID")
    merge = MergeColumn(verbose_name="keep | remove", accessor="pk")

    class Meta:
        model = Court
        sequence = ("id",)
        attrs = {"class": "table table-responsive table-hover"}


class CourtDecissionTable(tables.Table):
    id = tables.LinkColumn(verbose_name="Eurotort number")
    case_reference = tables.columns.TemplateColumn(
        template_code="<a href='{{ record.get_absolute_url }}'>{{ record.case_reference }}</a>",
        verbose_name="Case reference",
        orderable=False,
    )
    short_description = tables.TemplateColumn(
        template_code="{{ record.short_description|safe }}",
        verbose_name="Subject matter",
        orderable=False,
    )
    merge = MergeColumn(verbose_name="keep | remove", accessor="pk")
    keyword = tables.columns.ManyToManyColumn(verbose_name="Keywords")
    author = tables.columns.ManyToManyColumn(verbose_name="Authors")
    related_decision = tables.columns.ManyToManyColumn(verbose_name="Related decisions")
    tag = tables.columns.ManyToManyColumn(verbose_name="Tags")
    kwic = tables.columns.TemplateColumn(
        template_code="{{ record.kwic|safe }}",
        verbose_name="Search term in context",
        orderable=False,
    )

    class Meta:
        model = CourtDecission
        sequence = (
            "partial_legal_system",
            "decission_date",
            "court",
            "case_reference",
            "file_number",
            "party",
            "short_description",
            "kwic",
            "keyword",
            "tag",
            "situation",
            "motto",
            "commentary",
            "author",
            "year_book_title",
            "location",
            "related_decision",
            "additional_information",
            "ecli",
            "year_book_issue",
            "full_text",
            "modified_date",
        )
        attrs = {"class": "table table-responsive table-hover"}


class KeyWordTable(tables.Table):
    id = tables.LinkColumn(verbose_name="ID")
    merge = MergeColumn(verbose_name="keep | remove", accessor="pk")

    class Meta:
        model = KeyWord
        sequence = ("id",)
        attrs = {"class": "table table-responsive table-hover"}


class PartialLegalSystemTable(tables.Table):
    id = tables.LinkColumn(verbose_name="ID")
    merge = MergeColumn(verbose_name="keep | remove", accessor="pk")

    class Meta:
        model = PartialLegalSystem
        sequence = ("id", "name")
        attrs = {"class": "table table-responsive table-hover"}


class PersonTable(tables.Table):
    id = tables.LinkColumn(verbose_name="ID")
    legal_system = tables.columns.ManyToManyColumn(verbose_name="Legal system")
    merge = MergeColumn(verbose_name="keep | remove", accessor="pk")

    class Meta:
        model = Person
        sequence = ("id",)
        attrs = {"class": "table table-responsive table-hover"}


class TagTable(tables.Table):
    id = tables.LinkColumn(verbose_name="ID")
    merge = MergeColumn(verbose_name="keep | remove", accessor="pk")

    class Meta:
        model = Tag
        sequence = ("id",)
        attrs = {"class": "table table-responsive table-hover"}
