# Generated by Django 4.1.1 on 2023-08-30 09:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Country",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "legacy_id",
                    models.CharField(
                        blank=True, max_length=300, verbose_name="Legacy ID"
                    ),
                ),
                (
                    "legacy_pk",
                    models.IntegerField(
                        blank=True,
                        help_text="Primärschlüssel Alt",
                        null=True,
                        verbose_name="Primärschlüssel Alt",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        blank=True,
                        help_text="Name",
                        max_length=250,
                        verbose_name="Name",
                    ),
                ),
                (
                    "orig_data_csv",
                    models.TextField(
                        blank=True, null=True, verbose_name="The original data"
                    ),
                ),
            ],
            options={
                "verbose_name": "Country",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="Court",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "legacy_id",
                    models.CharField(
                        blank=True, max_length=300, verbose_name="Legacy ID"
                    ),
                ),
                (
                    "legacy_pk",
                    models.IntegerField(
                        blank=True,
                        help_text="Primärschlüssel Alt",
                        null=True,
                        verbose_name="Primärschlüssel Alt",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        blank=True,
                        help_text="Name",
                        max_length=250,
                        verbose_name="Name",
                    ),
                ),
                (
                    "abbreviation",
                    models.CharField(
                        blank=True,
                        help_text="Abbreviation",
                        max_length=250,
                        verbose_name="Abbreviation",
                    ),
                ),
                (
                    "is_high_court",
                    models.BooleanField(
                        blank=True,
                        default=False,
                        help_text="High Court",
                        null=True,
                        verbose_name="High Court",
                    ),
                ),
                (
                    "orig_data_csv",
                    models.TextField(
                        blank=True, null=True, verbose_name="The original data"
                    ),
                ),
                (
                    "country",
                    models.ForeignKey(
                        blank=True,
                        help_text="Country",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="rvn_court_country_country",
                        to="archiv.country",
                        verbose_name="country",
                    ),
                ),
            ],
            options={
                "verbose_name": "Court",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="Person",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "legacy_id",
                    models.CharField(
                        blank=True, max_length=300, verbose_name="Legacy ID"
                    ),
                ),
                (
                    "legacy_pk",
                    models.IntegerField(
                        blank=True,
                        help_text="Primärschlüssel Alt",
                        null=True,
                        verbose_name="Primärschlüssel Alt",
                    ),
                ),
                (
                    "last_name",
                    models.CharField(
                        blank=True,
                        help_text="Last Name",
                        max_length=250,
                        verbose_name="Last Name",
                    ),
                ),
                (
                    "first_name",
                    models.CharField(
                        blank=True,
                        help_text="First Name",
                        max_length=250,
                        verbose_name="First Name",
                    ),
                ),
                (
                    "cv",
                    models.TextField(
                        blank=True,
                        help_text="Vurriculum Vitae",
                        null=True,
                        verbose_name="Vurriculum Vitae",
                    ),
                ),
                (
                    "orig_data_csv",
                    models.TextField(
                        blank=True, null=True, verbose_name="The original data"
                    ),
                ),
                (
                    "nationality",
                    models.ForeignKey(
                        blank=True,
                        help_text="Nationality",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="rvn_person_nationality_country",
                        to="archiv.country",
                        verbose_name="Nationality",
                    ),
                ),
            ],
            options={
                "verbose_name": "Person",
                "ordering": ["last_name"],
            },
        ),
        migrations.CreateModel(
            name="PartialLegalSystem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "legacy_id",
                    models.CharField(
                        blank=True, max_length=300, verbose_name="Legacy ID"
                    ),
                ),
                (
                    "legacy_pk",
                    models.IntegerField(
                        blank=True,
                        help_text="Primärschlüssel Alt",
                        null=True,
                        verbose_name="Primärschlüssel Alt",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        blank=True,
                        help_text="name",
                        max_length=250,
                        verbose_name="name",
                    ),
                ),
                (
                    "orig_data_csv",
                    models.TextField(
                        blank=True, null=True, verbose_name="The original data"
                    ),
                ),
                (
                    "country",
                    models.ForeignKey(
                        blank=True,
                        help_text="Country",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="rvn_partiallegalsystem_country_country",
                        to="archiv.country",
                        verbose_name="country",
                    ),
                ),
            ],
            options={
                "verbose_name": "PartialLegalSystem",
                "ordering": ["legacy_pk"],
            },
        ),
        migrations.CreateModel(
            name="KeyWord",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "legacy_id",
                    models.CharField(
                        blank=True, max_length=300, verbose_name="Legacy ID"
                    ),
                ),
                (
                    "legacy_pk",
                    models.IntegerField(
                        blank=True,
                        help_text="Primärschlüssel Alt",
                        null=True,
                        verbose_name="Primärschlüssel Alt",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        blank=True,
                        help_text="Name",
                        max_length=250,
                        verbose_name="Name",
                    ),
                ),
                (
                    "orig_data_csv",
                    models.TextField(
                        blank=True, null=True, verbose_name="The original data"
                    ),
                ),
                (
                    "part_of",
                    models.ForeignKey(
                        blank=True,
                        help_text="Parent",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="rvn_keyword_part_of_keyword",
                        to="archiv.keyword",
                        verbose_name="Parent",
                    ),
                ),
            ],
            options={
                "verbose_name": "KeyWord",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="CourtDecission",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "legacy_id",
                    models.CharField(
                        blank=True, max_length=300, verbose_name="Legacy ID"
                    ),
                ),
                (
                    "legacy_pk",
                    models.IntegerField(
                        blank=True,
                        help_text="Primärschlüssel Alt",
                        null=True,
                        verbose_name="Primärschlüssel Alt",
                    ),
                ),
                (
                    "decission_date",
                    models.DateField(
                        blank=True, help_text="Date", null=True, verbose_name="Date"
                    ),
                ),
                (
                    "file_number",
                    models.CharField(
                        blank=True,
                        help_text="File Number",
                        max_length=250,
                        verbose_name="File Number",
                    ),
                ),
                (
                    "party",
                    models.CharField(
                        blank=True,
                        help_text="Parties",
                        max_length=250,
                        verbose_name="Parties",
                    ),
                ),
                (
                    "location",
                    models.TextField(
                        blank=True,
                        help_text="Decission Location",
                        null=True,
                        verbose_name="Decission Location",
                    ),
                ),
                (
                    "yearbook",
                    models.TextField(
                        blank=True,
                        help_text="Yearbook",
                        null=True,
                        verbose_name="Yearbook",
                    ),
                ),
                (
                    "short_description",
                    models.TextField(
                        blank=True,
                        help_text="Short Description",
                        null=True,
                        verbose_name="Short Description",
                    ),
                ),
                (
                    "situation",
                    models.TextField(
                        blank=True,
                        help_text="Sachverhalt",
                        null=True,
                        verbose_name="Sachverhalt",
                    ),
                ),
                (
                    "motto",
                    models.TextField(
                        blank=True,
                        help_text="Sachverhalt",
                        null=True,
                        verbose_name="Leitsatz",
                    ),
                ),
                (
                    "commentary",
                    models.TextField(
                        blank=True,
                        help_text="Kommentar",
                        null=True,
                        verbose_name="Kommentar",
                    ),
                ),
                (
                    "additional_information",
                    models.TextField(
                        blank=True,
                        help_text="Zusatzinfo",
                        null=True,
                        verbose_name="Zusatzinfo",
                    ),
                ),
                (
                    "orig_data_csv",
                    models.TextField(
                        blank=True, null=True, verbose_name="The original data"
                    ),
                ),
                (
                    "author",
                    models.ManyToManyField(
                        blank=True,
                        help_text="AutorIn",
                        related_name="rvn_courtdecission_author_person",
                        to="archiv.person",
                        verbose_name="AutorIn",
                    ),
                ),
                (
                    "country",
                    models.ForeignKey(
                        blank=True,
                        help_text="Country",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="rvn_courtdecission_country_country",
                        to="archiv.country",
                        verbose_name="Country",
                    ),
                ),
                (
                    "court",
                    models.ForeignKey(
                        blank=True,
                        help_text="Court",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="rvn_courtdecission_court_court",
                        to="archiv.court",
                        verbose_name="Court",
                    ),
                ),
                (
                    "keyword",
                    models.ManyToManyField(
                        blank=True,
                        help_text="Keywords",
                        related_name="rvn_courtdecission_keyword_keyword",
                        to="archiv.keyword",
                        verbose_name="Keywords",
                    ),
                ),
                (
                    "partial_legal_system",
                    models.ForeignKey(
                        blank=True,
                        help_text="PartialLegalSystem",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="rvn_courtdecission_partial_legal_system_partiallegalsystem",
                        to="archiv.partiallegalsystem",
                        verbose_name="PartialLegalSystem",
                    ),
                ),
            ],
            options={
                "verbose_name": "CourtDecission",
                "ordering": ["legacy_pk"],
            },
        ),
        migrations.AddField(
            model_name="court",
            name="partial_legal_system",
            field=models.ForeignKey(
                blank=True,
                help_text="Partial Legal System",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="rvn_court_partial_legal_system_partiallegalsystem",
                to="archiv.partiallegalsystem",
                verbose_name="Partial Legal System",
            ),
        ),
    ]
