# Generated by Django 4.2.4 on 2023-09-02 08:51

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("archiv", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="YearBook",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "title",
                    models.CharField(
                        blank=True,
                        help_text="Title",
                        max_length=250,
                        verbose_name="Title",
                    ),
                ),
            ],
            options={
                "verbose_name": "Yearbook",
                "ordering": ["title"],
            },
        ),
        migrations.AlterField(
            model_name="person",
            name="cv",
            field=models.TextField(
                blank=True,
                help_text="Curriculum Vitae",
                null=True,
                verbose_name="Curriculum Vitae",
            ),
        ),
    ]
