# Generated by Django 4.2.4 on 2023-09-02 09:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("archiv", "0002_yearbook_alter_person_cv"),
    ]

    operations = [
        migrations.AddField(
            model_name="courtdecission",
            name="year_book_issue",
            field=models.CharField(
                blank=True,
                help_text="Issue/Page",
                max_length=250,
                null=True,
                verbose_name="Year Book Issue/Page",
            ),
        ),
        migrations.AddField(
            model_name="courtdecission",
            name="year_book_title",
            field=models.ForeignKey(
                blank=True,
                help_text="Published in Year Book",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="related_court_decission",
                to="archiv.yearbook",
                verbose_name="Year Book",
            ),
        ),
    ]
