# Generated by Django 4.2.4 on 2023-09-09 10:12

import django.contrib.postgres.indexes
import django.contrib.postgres.search
from django.db import migrations
from django.db import models


class Migration(migrations.Migration):
    dependencies = [
        ("archiv", "0004_remove_courtdecission_yearbook_alter_yearbook_title"),
    ]

    operations = [
        migrations.AddField(
            model_name="courtdecission",
            name="full_text",
            field=models.TextField(
                blank=True,
                help_text="Fulltext field (technical field)",
                null=True,
                verbose_name="Fulltext field",
            ),
        ),
        migrations.AddField(
            model_name="courtdecission",
            name="vector_column",
            field=django.contrib.postgres.search.SearchVectorField(null=True),
        ),
        migrations.AddIndex(
            model_name="courtdecission",
            index=django.contrib.postgres.indexes.GinIndex(
                fields=["vector_column"], name="archiv_cour_vector__83d070_gin"
            ),
        ),
    ]
