# Generated by Django 4.2.4 on 2023-09-09 10:57

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("archiv", "0005_courtdecission_full_text_and_more"),
    ]

    operations = [
        migrations.RunSQL(
            sql="""
              CREATE TRIGGER vector_column_trigger
              BEFORE INSERT OR UPDATE OF full_text, vector_column
              ON archiv_courtdecission
              FOR EACH ROW EXECUTE PROCEDURE
              tsvector_update_trigger(
                vector_column, 'pg_catalog.english', full_text
              );

              UPDATE archiv_courtdecission SET vector_column = NULL;
            """,
            reverse_sql="""
              DROP TRIGGER IF EXISTS vector_column_trigger
              ON archiv_courtdecission;
            """,
        ),
    ]
