# Generated by Django 4.2.4 on 2023-10-18 10:31

from django.db import migrations
from django.db import models


class Migration(migrations.Migration):
    dependencies = [
        ("archiv", "0006_create_trigger"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="courtdecission",
            options={"ordering": ["id"], "verbose_name": "CourtDecission"},
        ),
        migrations.AlterModelOptions(
            name="partiallegalsystem",
            options={"ordering": ["id"], "verbose_name": "PartialLegalSystem"},
        ),
        migrations.RemoveField(
            model_name="court",
            name="country",
        ),
        migrations.RemoveField(
            model_name="courtdecission",
            name="country",
        ),
        migrations.RemoveField(
            model_name="partiallegalsystem",
            name="country",
        ),
        migrations.RemoveField(
            model_name="person",
            name="cv",
        ),
        migrations.RemoveField(
            model_name="person",
            name="nationality",
        ),
        migrations.AddField(
            model_name="person",
            name="contact",
            field=models.EmailField(
                blank=True,
                help_text="Email address",
                max_length=254,
                verbose_name="Contact",
            ),
        ),
        migrations.AddField(
            model_name="person",
            name="legal_system",
            field=models.ManyToManyField(
                blank=True,
                help_text="Legalsystem",
                related_name="has_related_author",
                to="archiv.partiallegalsystem",
                verbose_name="Legalsystem",
            ),
        ),
        migrations.AddField(
            model_name="person",
            name="orcid",
            field=models.URLField(
                blank=True, help_text="ORCID (as URL)", verbose_name="ORCID"
            ),
        ),
        migrations.DeleteModel(
            name="Country",
        ),
    ]
