# Generated by Django 4.2.4 on 2023-10-18 15:15

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("archiv", "0007_alter_courtdecission_options_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="courtdecission",
            options={"ordering": ["id"], "verbose_name": "Decision"},
        ),
        migrations.AlterModelOptions(
            name="partiallegalsystem",
            options={"ordering": ["id"], "verbose_name": "Legal System"},
        ),
        migrations.AddField(
            model_name="courtdecission",
            name="ecli",
            field=models.CharField(
                blank=True,
                help_text="European Case Law Identifier",
                max_length=250,
                null=True,
                verbose_name="ECLI",
            ),
        ),
        migrations.AddField(
            model_name="partiallegalsystem",
            name="ecli_abbr",
            field=models.CharField(
                blank=True,
                help_text="ECLI country code",
                max_length=2,
                null=True,
                verbose_name="ECLI country code",
            ),
        ),
        migrations.AddField(
            model_name="partiallegalsystem",
            name="link_to_legal_db",
            field=models.URLField(
                blank=True,
                help_text="Link to legal db",
                null=True,
                verbose_name="Link to legal db",
            ),
        ),
        migrations.AlterField(
            model_name="courtdecission",
            name="additional_information",
            field=models.TextField(
                blank=True,
                help_text="Additional Information",
                null=True,
                verbose_name="Additional Information",
            ),
        ),
        migrations.AlterField(
            model_name="courtdecission",
            name="author",
            field=models.ManyToManyField(
                blank=True,
                help_text="Authors",
                related_name="rvn_courtdecission_author_person",
                to="archiv.person",
                verbose_name="Authors",
            ),
        ),
        migrations.AlterField(
            model_name="courtdecission",
            name="commentary",
            field=models.TextField(
                blank=True, help_text="Commentary", null=True, verbose_name="Commentary"
            ),
        ),
        migrations.AlterField(
            model_name="courtdecission",
            name="decission_date",
            field=models.DateField(
                blank=True, help_text="Date of decision", null=True, verbose_name="Date"
            ),
        ),
        migrations.AlterField(
            model_name="courtdecission",
            name="file_number",
            field=models.CharField(
                blank=True,
                help_text="Case number",
                max_length=250,
                verbose_name="Case number",
            ),
        ),
        migrations.AlterField(
            model_name="courtdecission",
            name="location",
            field=models.TextField(
                blank=True,
                help_text="reported in",
                null=True,
                verbose_name="reported in",
            ),
        ),
        migrations.AlterField(
            model_name="courtdecission",
            name="motto",
            field=models.TextField(
                blank=True,
                help_text="Decision of the court",
                null=True,
                verbose_name="Decision",
            ),
        ),
        migrations.AlterField(
            model_name="courtdecission",
            name="short_description",
            field=models.TextField(
                blank=True,
                help_text="Brief description",
                null=True,
                verbose_name="Brief description",
            ),
        ),
        migrations.AlterField(
            model_name="courtdecission",
            name="situation",
            field=models.TextField(
                blank=True,
                help_text="Brief summary of the facst",
                null=True,
                verbose_name="Facst",
            ),
        ),
    ]
