# Generated by Django 4.2.4 on 2023-10-23 13:46

import django.db.models.deletion
from django.db import migrations
from django.db import models


class Migration(migrations.Migration):
    dependencies = [
        ("archiv", "0008_alter_courtdecission_options_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="yearbook",
            options={"ordering": ["title"], "verbose_name": "Bibliographic Item"},
        ),
        migrations.AddField(
            model_name="court",
            name="ecli_abbr",
            field=models.CharField(
                blank=True,
                help_text="ECLI court code",
                max_length=7,
                null=True,
                verbose_name="ECLI court code",
            ),
        ),
        migrations.AddField(
            model_name="keyword",
            name="introduction",
            field=models.TextField(
                blank=True,
                help_text="Introduction",
                null=True,
                verbose_name="Introduction",
            ),
        ),
        migrations.AddField(
            model_name="keyword",
            name="see_also",
            field=models.ManyToManyField(
                blank=True,
                help_text="related Keyword",
                to="archiv.keyword",
                verbose_name="related Keyword",
            ),
        ),
        migrations.AddField(
            model_name="yearbook",
            name="doi",
            field=models.URLField(
                blank=True, help_text="DOI (URL)", null=True, verbose_name="DOI"
            ),
        ),
        migrations.AlterField(
            model_name="court",
            name="is_high_court",
            field=models.BooleanField(
                blank=True,
                default=False,
                help_text="Highest Court",
                null=True,
                verbose_name="Highest Court",
            ),
        ),
        migrations.AlterField(
            model_name="court",
            name="partial_legal_system",
            field=models.ForeignKey(
                blank=True,
                help_text="Legalsystem",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="rvn_court_partial_legal_system_partiallegalsystem",
                to="archiv.partiallegalsystem",
                verbose_name="Legalsystem",
            ),
        ),
    ]
