# Generated by Django 4.2.4 on 2023-10-24 05:33

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("archiv", "0009_alter_yearbook_options_court_ecli_abbr_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Tag",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "tag",
                    models.CharField(
                        blank=True,
                        help_text="Tag",
                        max_length=300,
                        null=True,
                        verbose_name="Tag",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="courtdecission",
            name="tag",
            field=models.ManyToManyField(
                blank=True,
                help_text="Tags",
                related_name="has_related_keywords",
                to="archiv.tag",
                verbose_name="Tags",
            ),
        ),
    ]
