# Generated by Django 4.2.4 on 2023-10-24 05:50

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("archiv", "0010_tag_courtdecission_tag"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="tag",
            options={"ordering": ["tag"], "verbose_name": "Tag"},
        ),
    ]
