# Generated by Django 4.2.4 on 2023-11-10 10:13

from django.db import migrations
from django.db import models


class Migration(migrations.Migration):
    dependencies = [
        ("archiv", "0012_alter_court_options_alter_courtdecission_options_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="courtdecission",
            name="modified_date",
            field=models.DateTimeField(auto_now=True),
        ),
    ]
