# Generated by Django 4.2.4 on 2023-11-10 10:43

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("archiv", "0013_courtdecission_modified_date"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="partiallegalsystem",
            options={"ordering": ["id"], "verbose_name": "Legal system"},
        ),
    ]
