# Generated by Django 4.2.4 on 2023-12-04 15:43

import django.db.models.deletion
from django.db import migrations
from django.db import models


class Migration(migrations.Migration):
    dependencies = [
        ("archiv", "0014_alter_partiallegalsystem_options"),
    ]

    operations = [
        migrations.AlterField(
            model_name="court",
            name="is_high_court",
            field=models.BooleanField(
                blank=True,
                default=False,
                help_text="True if court is the highest court in a country",
                null=True,
                verbose_name="Highest Court",
            ),
        ),
        migrations.AlterField(
            model_name="courtdecission",
            name="court",
            field=models.ForeignKey(
                blank=True,
                help_text="Deciding court",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="rvn_courtdecission_court_court",
                to="archiv.court",
                verbose_name="Court",
            ),
        ),
        migrations.AlterField(
            model_name="keyword",
            name="see_also",
            field=models.ManyToManyField(
                blank=True,
                help_text="Related keyword(s)",
                to="archiv.keyword",
                verbose_name="related to",
            ),
        ),
        migrations.AlterField(
            model_name="partiallegalsystem",
            name="link_to_legal_db",
            field=models.URLField(
                blank=True,
                help_text="Link to legal database",
                null=True,
                verbose_name="Legal database",
            ),
        ),
        migrations.AlterField(
            model_name="person",
            name="legal_system",
            field=models.ManyToManyField(
                blank=True,
                help_text="Legal system",
                related_name="has_related_author",
                to="archiv.partiallegalsystem",
                verbose_name="Legal system",
            ),
        ),
        migrations.AlterField(
            model_name="yearbook",
            name="part_of",
            field=models.ForeignKey(
                blank=True,
                help_text="For chapters, select volume here",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="has_bibliographic_items",
                to="archiv.yearbook",
                verbose_name="Parent keyword",
            ),
        ),
    ]
