# Generated by Django 5.0 on 2023-12-07 12:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("archiv", "0016_alter_court_is_high_court_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="keyword",
            name="part_of",
            field=models.ForeignKey(
                blank=True,
                help_text="Parent keyword",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="rvn_keyword_part_of_keyword",
                to="archiv.keyword",
                verbose_name="Parent",
            ),
        ),
        migrations.AlterField(
            model_name="partiallegalsystem",
            name="name",
            field=models.CharField(
                blank=True, help_text="Name", max_length=250, verbose_name="Name"
            ),
        ),
    ]
