# Generated by Django 5.0 on 2024-01-06 08:54

import django.db.models.deletion
from django.db import migrations
from django.db import models


class Migration(migrations.Migration):
    dependencies = [
        ("archiv", "0017_alter_keyword_part_of_alter_partiallegalsystem_name"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="court",
            options={
                "ordering": ["name"],
                "verbose_name": "Court",
                "verbose_name_plural": "Courts",
            },
        ),
        migrations.AlterModelOptions(
            name="courtdecission",
            options={
                "ordering": ["id"],
                "verbose_name": "Case",
                "verbose_name_plural": "Cases",
            },
        ),
        migrations.AlterModelOptions(
            name="keyword",
            options={
                "ordering": ["name"],
                "verbose_name": "Keyword",
                "verbose_name_plural": "Keywords",
            },
        ),
        migrations.AlterModelOptions(
            name="partiallegalsystem",
            options={
                "ordering": ["name", "id"],
                "verbose_name": "Legal system",
                "verbose_name_plural": "Legal systems",
            },
        ),
        migrations.AlterModelOptions(
            name="person",
            options={
                "ordering": ["last_name"],
                "verbose_name": "Author",
                "verbose_name_plural": "Authors",
            },
        ),
        migrations.AlterModelOptions(
            name="tag",
            options={
                "ordering": ["tag"],
                "verbose_name": "Tag",
                "verbose_name_plural": "Tags",
            },
        ),
        migrations.AlterModelOptions(
            name="yearbook",
            options={
                "ordering": ["title"],
                "verbose_name": "Bibliographic Item",
                "verbose_name_plural": "Bibliographic Items",
            },
        ),
        migrations.AddField(
            model_name="yearbook",
            name="year",
            field=models.PositiveSmallIntegerField(
                blank=True,
                help_text="Publication Year",
                null=True,
                verbose_name="Publication Year",
            ),
        ),
        migrations.AlterField(
            model_name="court",
            name="partial_legal_system",
            field=models.ForeignKey(
                blank=True,
                help_text="Legal system",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="rvn_court_partial_legal_system_partiallegalsystem",
                to="archiv.partiallegalsystem",
                verbose_name="Legal system",
            ),
        ),
    ]
