# Generated by Django 5.0 on 2024-03-18 12:17

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("archiv", "0018_alter_court_options_alter_courtdecission_options_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="yearbook",
            options={
                "ordering": ["id"],
                "verbose_name": "Bibliographic Item",
                "verbose_name_plural": "Bibliographic Items",
            },
        ),
        migrations.RemoveField(
            model_name="court",
            name="legacy_id",
        ),
        migrations.RemoveField(
            model_name="court",
            name="legacy_pk",
        ),
        migrations.RemoveField(
            model_name="court",
            name="orig_data_csv",
        ),
        migrations.RemoveField(
            model_name="courtdecission",
            name="legacy_id",
        ),
        migrations.RemoveField(
            model_name="courtdecission",
            name="legacy_pk",
        ),
        migrations.RemoveField(
            model_name="courtdecission",
            name="orig_data_csv",
        ),
        migrations.RemoveField(
            model_name="keyword",
            name="legacy_id",
        ),
        migrations.RemoveField(
            model_name="keyword",
            name="legacy_pk",
        ),
        migrations.RemoveField(
            model_name="keyword",
            name="orig_data_csv",
        ),
        migrations.RemoveField(
            model_name="partiallegalsystem",
            name="legacy_id",
        ),
        migrations.RemoveField(
            model_name="partiallegalsystem",
            name="legacy_pk",
        ),
        migrations.RemoveField(
            model_name="person",
            name="legacy_id",
        ),
        migrations.RemoveField(
            model_name="person",
            name="legacy_pk",
        ),
        migrations.RemoveField(
            model_name="person",
            name="orig_data_csv",
        ),
    ]
