# Generated by Django 5.0 on 2024-07-08 05:58

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("archiv", "0019_alter_yearbook_options_remove_court_legacy_id_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="keyword",
            name="linked_to_cases",
            field=models.BooleanField(
                default=True,
                help_text="can be linked to cases",
                verbose_name="can be linked to cases",
            ),
        ),
        migrations.AlterField(
            model_name="courtdecission",
            name="file_number",
            field=models.CharField(
                blank=True,
                help_text="Case number (file number/reference as cited in the given legal system, e.g. '[2010] UKSC 33' for a UK Supreme Court decision or 'VI ZR 548/12' for a German BGH decision)",
                max_length=250,
                verbose_name="Case number",
            ),
        ),
    ]
