# Generated by Django 5.0 on 2024-07-19 13:23

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("archiv", "0021_alter_courtdecission_tag"),
    ]

    operations = [
        migrations.AlterField(
            model_name="courtdecission",
            name="tag",
            field=models.ManyToManyField(
                blank=True,
                help_text="Tags",
                related_name="has_related_decisions",
                to="archiv.tag",
                verbose_name="Tags",
            ),
        ),
    ]
