# Generated by Django 6.0.6 on 2026-09-24 09:57

import datetime

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("archiv", "0024_alter_courtdecission_decission_date_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="courtdecission",
            name="decission_date",
            field=models.DateField(
                default=datetime.date(1800, 1, 1),
                help_text="Date of decision (defaults to 1800-01-01)",
                verbose_name="Date",
            ),
        ),
        migrations.AlterField(
            model_name="courtdecission",
            name="year_book_issue",
            field=models.CharField(
                blank=True,
                help_text="Page/Paragraph/...",
                max_length=250,
                null=True,
                verbose_name="Page/Paragraph/...",
            ),
        ),
    ]
